### ISSUE TITLE
Strict validation of the Content-Type header

### ISSUE THREAD

**Issue by PatrykPlewaOfficial** [crowdin/crowdin-api-client-dotnet#103]
## Background

The `CrowdinApiClient` class contains a very strict validation when it comes to the `Content-Type` response header.

https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/CrowdinApiClient.cs#L323
```
private static readonly MediaTypeHeaderValue DefaultContentType = MediaTypeHeaderValue.Parse("application/json");
// ...
if (response.Content.Headers.ContentType.Equals(DefaultContentType))
```

I faced an issue with this validation while setting up a mock API for integration tests in my system.

Most of the modern WebApis return the header in such a way `Content-Type: application/json; charset=utf-8`.
This header value does not match the validation.

## Solution
The solution seems pretty easy to develop. Easing the validation should not break any of the working parts of the client.

**Comment by innomaxx** [comment]
Hello @PatrykPlewaOfficial,

Thank you for paying attention to this. We will fix it asap.

**Comment by innomaxx** [comment]
https://github.com/crowdin/crowdin-api-client-dotnet/pull/104
