### ISSUE TITLE
Projects API: `qaChecksIgnorableCategories` support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#113]
Crowdin Rest API now supports the `qaChecksIgnorableCategories` field on the Projects API.

This field allows you to retrieve the list of QA Check categories that can be ignored for a Crowdin project.

Affected API methods:

- [Add project](https://developer.crowdin.com/api/v2/#operation/api.projects.post) (request schema)
- [Project settings response model](https://developer.crowdin.com/api/v2/#operation/api.projects.get)
- [Edit Project](https://developer.crowdin.com/api/v2/#operation/api.projects.patch) (request schema)

It should be reflected in this API client and the corresponding unit tests should be updated.

**Comment by innomaxx** [comment]
@andrii-bodnar type of `qaChecksIgnorableCategories` is the same that of `qaCheckCategories`? Seems like props are the same

**Comment by andrii-bodnar** [comment]
> Also in docs I noticed new properties in `qaCheckCategories` model that are also exist in `qaChecksIgnorableCategories` But these props are not available in API client yet. Should we also add them?

Nice catch, these are new types that have been added recently, they should be reflected in the API client as well

**Comment by innomaxx** [comment]
> Please provide the API methods as a reference, probably it's the same, but need to check additionally

It's [Add Project](https://developer.crowdin.com/api/v2/#operation/api.projects.post) method

**Comment by andrii-bodnar** [comment]
> type of qaChecksIgnorableCategories is the same that of qaCheckCategories? Seems like props are the same

yes, it's the same
