### ISSUE TITLE
Missing Project webhook types

### ISSUE THREAD

**Issue by PatrykPlewaOfficial** [crowdin/crowdin-api-client-dotnet#120]
During my attempt to implement automated project webhooks management, I discovered that some of the events are missing in the [file](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/Webhooks/EventType.cs):
```cs
    [PublicAPI]
    public enum EventType
    {
        [Description("file.translated")]        FileTranslated,
        [Description("file.approved")]        FileApproved,
        [Description("project.translated")]        ProjectTranslated,
        [Description("project.approved")]        ProjectApproved,
        [Description("translation.updated")]        TranslationUpdated,
        [Description("string.added")]        StringAdded,
        [Description("string.updated")]        StringUpdated,
        [Description("string.deleted")]        StringDeleted,
        [Description("suggestion.added")]        SuggestionAdded,
        [Description("suggestion.updated")]        SuggestionUpdated,
        [Description("suggestion.deleted")]        SuggestionDeleted,
        [Description("suggestion.approved")]        SuggestionApproved,
        [Description("suggestion.disapproved")]        SuggestionDisapproved
    }
```

The missing ones are for instance: `file.added` or `file.updated`.

Is there a particular reason why they were not included in the client?

**Comment by andrii-bodnar** [comment]
Hi @PatrykPlewaOfficial, thanks for reporting this!

probably some mistake has occurred, there is no reason not to include these types here.

Would you like to raise a PR?

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial thank you!

**Comment by PatrykPlewaOfficial** [comment]
Came up with #121.
Please verify the spelling because it's super easy to make a mistake 😃
