### ISSUE TITLE
Webhooks listing JSON parsing issue

### ISSUE THREAD

**Issue by PatrykPlewaOfficial** [crowdin/crowdin-api-client-dotnet#123]
# Issue

Listing webhooks for a project throws an exception

```cs
Unexpected character encountered while parsing value: {. Path 'payload['project.approved'].project', line 15, position 18.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Crowdin.Api.Core.JsonParser.ParseResponseObject[TData](JObject rootElement) in JsonParser.cs:line 38
   at System.Linq.Enumerable.SelectIListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Crowdin.Api.Core.JsonParser.ParseResponseList[TData](JObject rootElement) in JsonParser.cs:line 41
   at Crowdin.Api.Webhooks.WebhooksApiExecutor.<ListWebhooks>d__4.MoveNext() in WebhooksApiExecutor.cs:line 39
   at Program.<<Main>$>d__0.MoveNext()
```

which is caused by an invalid type for the `payload` property.

# Cause

Given an example webhook JSON response (Crowdin's default payload):

```json
[
    {
      "data": {
        "id": 9,
        "projectId": 7,
        "name": "File proofreading complete",
        "url": "https://something.com",
        "events": ["project.approved"],
        "headers": {
          "x-api-key": "secret"
        },
        "payload": {
          "project.approved": {
            "event": "{{event}}",
            "project": {
              "id": "{{projectId}}",
              "userId": "{{projectUserId}}",
              "sourceLanguageId": "{{projectSourceLanguageId}}",
              "targetLanguageIds": "{{projectTargetLanguageIds}}",
              "identifier": "{{projectIdentifier}}",
              "name": "{{projectName}}",
              "createdAt": "{{projectCreatedAt}}",
              "updatedAt": "{{projectUpdatedAt}}",
              "lastActivity": "{{projectLastActivity}}",
              "description": "{{projectDescription}}",
              "url": "{{projectUrl}}",
              "cname": "{{projectCname}}",
              "logo": "{{projectLogo}}",
              "isExternal": "{{projectIsExternal}}",
              "externalType": "{{projectExternalType}}",
              "hasCrowdsourcing": "{{projectHasCrowdsourcing}}"
            },
            "targetLanguage": {
              "id": "{{targetLanguageId}}",
              "name": "{{targetLanguageName}}",
              "editorCode": "{{targetLanguageEditorCode}}",
              "twoLettersCode": "{{targetLanguageTwoLettersCode}}",
              "threeLettersCode": "{{targetLanguageThreeLettersCode}}",
              "locale": "{{targetLanguageLocale}}",
              "androidCode": "{{targetLanguageAndroidCode}}",
              "osxCode": "{{targetLanguageOsxCode}}",
              "osxLocale": "{{targetLanguageOsxLocale}}",
              "textDirection": "{{targetLanguageTextDirection}}",
              "dialectOf": "{{targetLanguageDialectOf}}"
            }
          }
        },
        "isActive": true,
        "batchingEnabled": false,
        "requestType": "POST",
        "contentType": "application/json",
        "createdAt": "2023-05-05T10:22:40+02:00",
        "updatedAt": "2023-05-05T10:22:40+02:00"
      }
    }
  ]
```
and the CSharp model

```cs
public class Webhook
  {
// ...
    [JsonProperty("payload")]
    public IDictionary<string, IDictionary<string, string>> Payload { get; set; }
  }
```

as we can see, the property `Payload` is of type `IDictionary<string, IDictionary<string, string>>`. However, things get worse when we look at the JSON file property `payload['project.approved'].project`. `JsonConverter` expects it to be of type `string` however there is another `Dictionary` here.

# Potential solution

The `AddWebhook` request accepts the `Payload` property just as `object`. Maybe using `object` type in the response would resolve that problem.

Or maybe in both cases, the `Payload` property should be of type string, accepting any object already serialized to a JSON string?

**Comment by PatrykPlewaOfficial** [comment]
My tests showed that switching the `Payload` property to `object` type fixes the listing operation.

However, the `AddWebhook` operation is also corrupted.
Given Crowdin's default payload (for `TranslationUpdated`) I experience another error:

```
Error converting value "{{event}}" to type 'System.Collections.Generic.IDictionary`2[System.String,System.String]'. Path 'payload.event', line 13, position 24.
Could not cast or convert from System.String to System.Collections.Generic.IDictionary`2[System.String,System.String].
```

This time the `event` property is of wrong type:
```json
{
    "event": "{{event}}",
    "oldTranslation": {
        "id": "{{oldTranslationId}}",
        "text": "{{oldTranslationText}}",
        "pluralCategoryName": "{{oldTranslationPluralCategoryName}}",
        "rating": "{{oldTranslationRating}}",
        "createdAt": "{{oldTranslationCreatedAt}}"
    },
   //...
}
```

**Comment by PatrykPlewaOfficial** [comment]
Another problem appears with `AddWebhook` operation. The `Payload` provided in the request does not match the `Payload` that appears in Crowdin UI.

Request payload (Crowdin's default):

```json
{
  "name": "Exported translation updated",
  "url": "http://localhost:5000/api/translation/updated",
  "events": ["translation.updated"],
  "requestType": "POST",
  "isActive": true,
  "batchingEnabled": false,
  "contentType": "application/json",
  "headers": { "x-api-key": "secret" },
  "payload": {
    "event": "{{event}}",
    "oldTranslation": {
      "id": "{{oldTranslationId}}",
      "text": "{{oldTranslationText}}",
      "pluralCategoryName": "{{oldTranslationPluralCategoryName}}",
      "rating": "{{oldTranslationRating}}",
      "createdAt": "{{oldTranslationCreatedAt}}"
    },
    "newTranslation": {
      "id": "{{newTranslationId}}",
      "text": "{{newTranslationText}}",
      "pluralCategoryName": "{{newTranslationPluralCategoryName}}",
      "rating": "{{newTranslationRating}}",
      "createdAt": "{{newTranslationCreatedAt}}",
      "user": {
        "id": "{{userId}}",
        "username": "{{userUsername}}",
        "fullName": "{{userFullName}}",
        "avatarUrl": "{{userAvatarUrl}}"
      },
      "targetLanguage": {
        "id": "{{targetLanguageId}}",
        "name": "{{targetLanguageName}}",
        "editorCode": "{{targetLanguageEditorCode}}",
        "twoLettersCode": "{{targetLanguageTwoLettersCode}}",
        "threeLettersCode": "{{targetLanguageThreeLettersCode}}",
        "locale": "{{targetLanguageLocale}}",
        "androidCode": "{{targetLanguageAndroidCode}}",
        "osxCode": "{{targetLanguageOsxCode}}",
        "osxLocale": "{{targetLanguageOsxLocale}}",
        "textDirection": "{{targetLanguageTextDirection}}",
        "dialectOf": "{{targetLanguageDialectOf}}"
      },
      "string": {
        "id": "{{stringId}}",
        "identifier": "{{stringIdentifier}}",
        "key": "{{stringKey}}",
        "text": "{{stringText}}",
        "type": "{{stringType}}",
        "context": "{{stringContext}}",
        "maxLength": "{{stringMaxLength}}",
        "isHidden": "{{stringIsHidden}}",
        "isDuplicate": "{{stringIsDuplicate}}",
        "masterStringId": "{{stringMasterStringId}}",
        "revision": "{{stringRevision}}",
        "hasPlurals": "{{stringHasPlurals}}",
        "labelIds": "{{stringLabelIds}}",
        "url": "{{stringUrl}}",
        "createdAt": "{{stringCreatedAt}}",
        "updatedAt": "{{stringUpdatedAt}}",
        "file": {
          "id": "{{fileId}}",
          "name": "{{fileName}}",
          "title": "{{fileTitle}}",
          "type": "{{fileType}}",
          "path": "{{filePath}}",
          "status": "{{fileStatus}}",
          "revision": "{{fileRevision}}",
          "branchId": "{{branchId}}",
          "directoryId": "{{directoryId}}"
        },
        "project": {
          "id": "{{projectId}}",
          "userId": "{{projectUserId}}",
          "sourceLanguageId": "{{projectSourceLanguageId}}",
          "targetLanguageIds": "{{projectTargetLanguageIds}}",
          "identifier": "{{projectIdentifier}}",
          "name": "{{projectName}}",
          "createdAt": "{{projectCreatedAt}}",
          "updatedAt": "{{projectUpdatedAt}}",
          "lastActivity": "{{projectLastActivity}}",
          "description": "{{projectDescription}}",
          "url": "{{projectUrl}}",
          "cname": "{{projectCname}}",
          "logo": "{{projectLogo}}",
          "isExternal": "{{projectIsExternal}}",
          "externalType": "{{projectExternalType}}",
          "hasCrowdsourcing": "{{projectHasCrowdsourcing}}"
        }
      }
    }
  }
}
```

Payload that appears in Crowdin UI:

```json
{
    "event": "{{event}}",
    "project": "{{projectIdentifier}}",
    "project_id": "{{projectId}}",
    "language": "{{targetLanguageId}}",
    "source_string_id": "{{stringId}}",
    "old_translation_id": "{{oldTranslationId}}",
    "new_translation_id": "{{newTranslationId}}",
    "user": "{{userFullName}}",
    "user_id": "{{userId}}",
    "file_id": "{{fileId}}",
    "file": "{{filePath}}"
}
```

**Comment by ira-sem** [comment]
Hi @PatrykPlewaOfficial ! Checking on our side

**Comment by ira-sem** [comment]
@PatrykPlewaOfficial small update: our team is aware of it and will work on the fix

**Comment by innomaxx** [comment]
Hi @PatrykPlewaOfficial!
Thanks for your issue and investigation. Fixed in #128 + added tests.

**Comment by PatrykPlewaOfficial** [comment]
Hi guys, great news 👍 .

How about this issue?

> Another problem appears with `AddWebhook` operation. The `Payload` provided in the request does not match the `Payload` that appears in Crowdin UI.
> 
> Request payload (Crowdin's default):
> 
> ```json
> {
>   "name": "Exported translation updated",
>   "url": "http://localhost:5000/api/translation/updated",
>   "events": ["translation.updated"],
>   "requestType": "POST",
>   "isActive": true,
>   "batchingEnabled": false,
>   "contentType": "application/json",
>   "headers": { "x-api-key": "secret" },
>   "payload": {
>     "event": "{{event}}",
>     "oldTranslation": {
>       "id": "{{oldTranslationId}}",
>       "text": "{{oldTranslationText}}",
>       "pluralCategoryName": "{{oldTranslationPluralCategoryName}}",
>       "rating": "{{oldTranslationRating}}",
>       "createdAt": "{{oldTranslationCreatedAt}}"
>     },
>     "newTranslation": {
>       "id": "{{newTranslationId}}",
>       "text": "{{newTranslationText}}",
>       "pluralCategoryName": "{{newTranslationPluralCategoryName}}",
>       "rating": "{{newTranslationRating}}",
>       "createdAt": "{{newTranslationCreatedAt}}",
>       "user": {
>         "id": "{{userId}}",
>         "username": "{{userUsername}}",
>         "fullName": "{{userFullName}}",
>         "avatarUrl": "{{userAvatarUrl}}"
>       },
>       "targetLanguage": {
>         "id": "{{targetLanguageId}}",
>         "name": "{{targetLanguageName}}",
>         "editorCode": "{{targetLanguageEditorCode}}",
>         "twoLettersCode": "{{targetLanguageTwoLettersCode}}",
>         "threeLettersCode": "{{targetLanguageThreeLettersCode}}",
>         "locale": "{{targetLanguageLocale}}",
>         "androidCode": "{{targetLanguageAndroidCode}}",
>         "osxCode": "{{targetLanguageOsxCode}}",
>         "osxLocale": "{{targetLanguageOsxLocale}}",
>         "textDirection": "{{targetLanguageTextDirection}}",
>         "dialectOf": "{{targetLanguageDialectOf}}"
>       },
>       "string": {
>         "id": "{{stringId}}",
>         "identifier": "{{stringIdentifier}}",
>         "key": "{{stringKey}}",
>         "text": "{{stringText}}",
>         "type": "{{stringType}}",
>         "context": "{{stringContext}}",
>         "maxLength": "{{stringMaxLength}}",
>         "isHidden": "{{stringIsHidden}}",
>         "isDuplicate": "{{stringIsDuplicate}}",
>         "masterStringId": "{{stringMasterStringId}}",
>         "revision": "{{stringRevision}}",
>         "hasPlurals": "{{stringHasPlurals}}",
>         "labelIds": "{{stringLabelIds}}",
>         "url": "{{stringUrl}}",
>         "createdAt": "{{stringCreatedAt}}",
>         "updatedAt": "{{stringUpdatedAt}}",
>         "file": {
>           "id": "{{fileId}}",
>           "name": "{{fileName}}",
>           "title": "{{fileTitle}}",
>           "type": "{{fileType}}",
>           "path": "{{filePath}}",
>           "status": "{{fileStatus}}",
>           "revision": "{{fileRevision}}",
>           "branchId": "{{branchId}}",
>           "directoryId": "{{directoryId}}"
>         },
>         "project": {
>           "id": "{{projectId}}",
>           "userId": "{{projectUserId}}",
>           "sourceLanguageId": "{{projectSourceLanguageId}}",
>           "targetLanguageIds": "{{projectTargetLanguageIds}}",
>           "identifier": "{{projectIdentifier}}",
>           "name": "{{projectName}}",
>           "createdAt": "{{projectCreatedAt}}",
>           "updatedAt": "{{projectUpdatedAt}}",
>           "lastActivity": "{{projectLastActivity}}",
>           "description": "{{projectDescription}}",
>           "url": "{{projectUrl}}",
>           "cname": "{{projectCname}}",
>           "logo": "{{projectLogo}}",
>           "isExternal": "{{projectIsExternal}}",
>           "externalType": "{{projectExternalType}}",
>           "hasCrowdsourcing": "{{projectHasCrowdsourcing}}"
>         }
>       }
>     }
>   }
> }
> ```
> 
> Payload that appears in Crowdin UI:
> 
> ```json
> {
>     "event": "{{event}}",
>     "project": "{{projectIdentifier}}",
>     "project_id": "{{projectId}}",
>     "language": "{{targetLanguageId}}",
>     "source_string_id": "{{stringId}}",
>     "old_translation_id": "{{oldTranslationId}}",
>     "new_translation_id": "{{newTranslationId}}",
>     "user": "{{userFullName}}",
>     "user_id": "{{userId}}",
>     "file_id": "{{fileId}}",
>     "file": "{{filePath}}"
> }
> ```

is this related to the client? Has this been fixed as well? Let me know.

**Comment by PatrykPlewaOfficial** [comment]
@andrii-bodnar How about the other issue above? 😉

**Comment by andrii-bodnar** [comment]
@innomaxx could you please take a look?

**Comment by innomaxx** [comment]
@PatrykPlewaOfficial thanks for your investigation. We will check it on our side asap

**Comment by PatrykPlewaOfficial** [comment]
Please reopen until the investigation is finished 😉

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial thanks for the investigation, I will check it on the API side in more detail and then will come back as soon as possible

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial recently we've enhanced the webhook payloads and now it includes much more data than before. It seems like your webhook was created before that and uses the old format (I mean this: `Payload that appears in Crowdin UI`). It was kept in the old format for compatibility. But the new webhooks created via API or UI will have the new enhanced data.

**Comment by PatrykPlewaOfficial** [comment]
Hi @andrii-bodnar .
I kinda don't understand that answer.

There is an API endpoint to create a new webhook of a desired payload - a payload of my choice.
However, the endpoint does not work correctly. I expect my payload to appear in Crowdin but I see something completely different.

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial probably I misunderstood the request. Could you please share in more detail what do you mean by "appear in Crowdin"?

**Comment by PatrykPlewaOfficial** [comment]
Sure @andrii-bodnar ,
This is how my payload in the request look like
```
{
  "name": "Exported translation updated",
  "url": "http://localhost:5000/api/translation/updated",
  "events": ["translation.updated"],
  "requestType": "POST",
  "isActive": true,
  "batchingEnabled": false,
  "contentType": "application/json",
  "headers": { "x-api-key": "secret" },
  "payload": {
    "event": "{{event}}",
    "oldTranslation": {
      "id": "{{oldTranslationId}}",
      "text": "{{oldTranslationText}}",
      "pluralCategoryName": "{{oldTranslationPluralCategoryName}}",
      "rating": "{{oldTranslationRating}}",
      "createdAt": "{{oldTranslationCreatedAt}}"
    },
    "newTranslation": {
      "id": "{{newTranslationId}}",
      "text": "{{newTranslationText}}",
      "pluralCategoryName": "{{newTranslationPluralCategoryName}}",
      "rating": "{{newTranslationRating}}",
      "createdAt": "{{newTranslationCreatedAt}}",
      "user": {
        "id": "{{userId}}",
        "username": "{{userUsername}}",
        "fullName": "{{userFullName}}",
        "avatarUrl": "{{userAvatarUrl}}"
      },
      "targetLanguage": {
        "id": "{{targetLanguageId}}",
        "name": "{{targetLanguageName}}",
        "editorCode": "{{targetLanguageEditorCode}}",
        "twoLettersCode": "{{targetLanguageTwoLettersCode}}",
        "threeLettersCode": "{{targetLanguageThreeLettersCode}}",
        "locale": "{{targetLanguageLocale}}",
        "androidCode": "{{targetLanguageAndroidCode}}",
        "osxCode": "{{targetLanguageOsxCode}}",
        "osxLocale": "{{targetLanguageOsxLocale}}",
        "textDirection": "{{targetLanguageTextDirection}}",
        "dialectOf": "{{targetLanguageDialectOf}}"
      },
      "string": {
        "id": "{{stringId}}",
        "identifier": "{{stringIdentifier}}",
        "key": "{{stringKey}}",
        "text": "{{stringText}}",
        "type": "{{stringType}}",
        "context": "{{stringContext}}",
        "maxLength": "{{stringMaxLength}}",
        "isHidden": "{{stringIsHidden}}",
        "isDuplicate": "{{stringIsDuplicate}}",
        "masterStringId": "{{stringMasterStringId}}",
        "revision": "{{stringRevision}}",
        "hasPlurals": "{{stringHasPlurals}}",
        "labelIds": "{{stringLabelIds}}",
        "url": "{{stringUrl}}",
        "createdAt": "{{stringCreatedAt}}",
        "updatedAt": "{{stringUpdatedAt}}",
        "file": {
          "id": "{{fileId}}",
          "name": "{{fileName}}",
          "title": "{{fileTitle}}",
          "type": "{{fileType}}",
          "path": "{{filePath}}",
          "status": "{{fileStatus}}",
          "revision": "{{fileRevision}}",
          "branchId": "{{branchId}}",
          "directoryId": "{{directoryId}}"
        },
        "project": {
          "id": "{{projectId}}",
          "userId": "{{projectUserId}}",
          "sourceLanguageId": "{{projectSourceLanguageId}}",
          "targetLanguageIds": "{{projectTargetLanguageIds}}",
          "identifier": "{{projectIdentifier}}",
          "name": "{{projectName}}",
          "createdAt": "{{projectCreatedAt}}",
          "updatedAt": "{{projectUpdatedAt}}",
          "lastActivity": "{{projectLastActivity}}",
          "description": "{{projectDescription}}",
          "url": "{{projectUrl}}",
          "cname": "{{projectCname}}",
          "logo": "{{projectLogo}}",
          "isExternal": "{{projectIsExternal}}",
          "externalType": "{{projectExternalType}}",
          "hasCrowdsourcing": "{{projectHasCrowdsourcing}}"
        }
      }
    }
  }
}
```

This is the same exact payload visible in API Log in Crowdin
![image](https://github.com/crowdin/crowdin-api-client-dotnet/assets/47867089/b55ea852-31d2-4b71-95e3-02aa22b026e6)

And finally, this is what I see as a payload of my created webhook on Webhooks page (Crowdin UI)
![image](https://github.com/crowdin/crowdin-api-client-dotnet/assets/47867089/8acfd7e6-fe24-4813-82cf-deb910f4b9f1)

which is completely different than my request.

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial thank you, I was able to reproduce this issue. It's something not related to the Crowdin .NET client. Passing it to the team.

**Comment by andrii-bodnar** [comment]
The development team has looked into this and confirmed that the current behavior is correct.

The request payload above is incorrect and should have the following structure:

```
{
  "payload": {
    "string.added": {...},
    "string.updated": {...},
    "string.deleted": {...}
  }
}
```

Please refer to the [API documentation](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.webhooks.post) to see the full valid example (The _Request samples_ section).
