### ISSUE TITLE
`ExportProjectTranslation`: CrowdinApiException: Invalid Request Parameters: Key [format]: Value is required and can't be empty

### ISSUE THREAD

**Issue by d2phap** [crowdin/crowdin-api-client-dotnet#158]
Hi,

I tried to call the `ExportProjectTranslation` API with the below code:
```cs
var downloadLink = await _crowdin.Translations.ExportProjectTranslation(projectId, new ExportProjectTranslationRequest()
{
    TargetLanguageId = langId,
});
```

I got this error:
<img width="1322" alt="image" src="https://github.com/crowdin/crowdin-api-client-dotnet/assets/3154213/ba6d6ddb-181a-44a9-855b-17e032bb34ea">

Note that, I want to get the original file format so I didn't pass `Format` property (according to https://developer.crowdin.com/api/v2/#operation/api.projects.translations.exports.post):
> Note: the format parameter is required in all cases except when you'd like to export translations for a single file in its original format

I also tried passing the format, but the `TranslationFormat` enum does not have the "original" option.

Please help, thank you!

**Comment by andrii-bodnar** [comment]
Hi @d2phap!

This API method can export only a single file in the "original" file format and in this case, you should pass the File ID in the `fileIds` parameter.

In case you need to export multiple files in the original format for the specified language, you should use the [Build Project Translation](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.builds.post) + [Check Project Build Status](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.builds.get) and [Download Project Translations](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.builds.download.download).

See the [6_DownloadTranslations.cs](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/samples/Crowdin.Api.Samples.Actions/Actions/6_DownloadTranslations.cs) example for more details.

**Comment by d2phap** [comment]
Thanks @andrii-bodnar for help! It works.
