### ISSUE TITLE
Create Task API: new `includePreTranslatedStringsOnly` parameter

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#163]
API Reference: [Add Task](https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.post)

The API response will also include this new field.

This is relevant for both the crowdin.com and Crowdin Enterprise APIs.

The new parameter should also be reflected in this API client.

**Comment by Riju-bak** [comment]
Hi @andrii-bodnar, can I take this up?

**Comment by andrii-bodnar** [comment]
Hi @Riju-bak, sure, thank you!

**Comment by Riju-bak** [comment]
@andrii-bodnar Can you please look at the description of the draft PR, to see if I correctly understood the problem.

Also, I'm not sure how I can test requests to add tasks.
 I had a look at the tests in [TasksApiTests.cs](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/tests/Crowdin.Api.Tests/Tasks/TasksApiTests.cs). It seems that the tests within this file only check whether the AddTaskRequest object is getting serialized correctly.

**Comment by andrii-bodnar** [comment]
Hi @Riju-bak, thanks a lot for the contribution! The PR looks good to me. You probably need to add this new parameter to the existing Unit test and that's it. @innomaxx please correct me if I'm wrong.

**Comment by Riju-bak** [comment]
@andrii-bodnar @innomaxx I have opened this [PR](https://github.com/crowdin/crowdin-api-client-dotnet/pull/165), but unbale to add reviewers, so just posting it here.
