### ISSUE TITLE
Distributions API changes

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#172]
The Distribution creation API has been changed. Now you can create a distribution with the following parameters:

- `bundleIds` - array of bundle ids

The following parameters have been deprecated:

- `format`
- `exportPattern`
- `labelIds`

A Distribution response has also been changed. Now it contains the `bundleIds` field. The `format`, `exportPattern`, and `labelIds` fields are deprecated.

In addition, the `fileIds` request parameter is now _optional_.

All the changes are described in the [API documentation](https://developer.crowdin.com/api/v2/#operation/api.projects.distributions.post).

**Comment by Riju-bak** [comment]
Hi @andrii-bodnar, can you assign this to me. I already have a working fix. Just need to update the tests and check.

**Comment by andrii-bodnar** [comment]
Hi @Riju-bak, sure, thanks a lot!

**Comment by Riju-bak** [comment]
@andrii-bodnar Here's the [PR](https://github.com/crowdin/crowdin-api-client-dotnet/pull/173)
