### ISSUE TITLE
AddProjectRequest class is empty

### ISSUE THREAD

**Issue by bZverok** [crowdin/crowdin-api-client-dotnet#174]
AddProjectRequest class is empty, although there are a lot of request parameters in the documentation for this request(https://developer.crowdin.com/api/v2/#operation/api.projects.post)

![зображення](https://github.com/crowdin/crowdin-api-client-dotnet/assets/137277669/5ccab780-bc56-461b-93d3-207a04ca4d49)

**Comment by andrii-bodnar** [comment]
Hi @bZverok, this is just a base class for the [ProjectForm.cs](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/ProjectsGroups/ProjectForm.cs) and [EnterpriseProjectForm.cs](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/ProjectsGroups/EnterpriseProjectForm.cs). The first one is supposed to be used in crowdin.com, and the second one in Crowdin Enterprise.

**Comment by bZverok** [comment]
ProjectFrom.cs has only one property, but there are much more in the non-enterprise version of documentation ((https://developer.crowdin.com/api/v2/#operation/api.projects.post).

**Comment by andrii-bodnar** [comment]
@bZverok yes, I just noticed that too, we should definitely add the missing properties

**Comment by innomaxx** [comment]
> @bZverok yes, I just noticed that too, we should definitely add the missing properties

`ProjectForm` type is abstract and not supposed to use. Users should use its derived types

![image](https://github.com/crowdin/crowdin-api-client-dotnet/assets/40697586/55518e96-ea08-4fef-8fc6-afce15d8316c)
