### ISSUE TITLE
Webhook responses are not deserialized correctly

### ISSUE THREAD

**Issue by bZverok** [crowdin/crowdin-api-client-dotnet#176]
Everytime I invoke methods that receive webhook info (addWebhook, listWebhooks, etc. ) it throws an exception(see screenshot below). It occurs with organizationWebhooks and webhooks. I suppose that it has something to do with the Headers property

![зображення](https://github.com/crowdin/crowdin-api-client-dotnet/assets/137277669/b32099d2-13fc-4409-af95-c0f3eef81cc5)

**Comment by bZverok** [comment]
Here is how I use sdk: 
![зображення](https://github.com/crowdin/crowdin-api-client-dotnet/assets/137277669/05eb22ab-b957-4f40-9a4d-b4fe9ebca160)

**Comment by bZverok** [comment]
Here is the request: 
![зображення](https://github.com/crowdin/crowdin-api-client-dotnet/assets/137277669/a248b276-1278-40dc-8636-cdd32dcf6d39)

**Comment by bZverok** [comment]
It is also weird that OrganizationWebhooksApiExecutor is not a part of CrowdinApiClient, so that I need to create its instance manually

**Comment by innomaxx** [comment]
> Here is the request: ![зображення](https://user-images.githubusercontent.com/137277669/256295734-a248b276-1278-40dc-8636-cdd32dcf6d39.png)

Thanks for clarifications. I see the issue : API returns `headers` as JSON Array instead of JSON Object. Seems like it should be fixed on backend side or handled in SDK. We will discuss this moment asap

**Comment by innomaxx** [comment]
> It is also weird that OrganizationWebhooksApiExecutor is not a part of CrowdinApiClient, so that I need to create its instance manually

It's an issue, I will fix it. Thanks for mentioning this.

**Comment by innomaxx** [comment]
@andrii-bodnar @bZverok #180. It's probably temporary solution. Now it applied specifically to `Headers` property. The custom converter I implemented also can be added to any property with the same deserialization issue. I also added test case with sample broken json response to check the algorithm

**Comment by bZverok** [comment]
Glad to hear that! Looking forward to seeing this update on a nuget

**Comment by andrii-bodnar** [comment]
@bZverok available in [2.16.0](https://github.com/crowdin/crowdin-api-client-dotnet/releases/tag/2.16.0)
