### ISSUE TITLE
API 2.0 support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#19]
[Announcement](https://blog.crowdin.com/2020/08/05/announcing-the-new-API-2.0/)

[Docs](https://support.crowdin.com/api/v2/)
[Docs Enterprise](https://support.crowdin.com/enterprise/api/)

**Comment by henk-van-der-vaart** [comment]
We NEC Nederland B.V. are a current user (from start of availability) of the API v1 .NET client (available as NuGet).
Since API v1 support will stop end 2021 we hope API v2 .NET client will be available in time given us enough time to adapt our tooling (code changes, review and testing).

**Comment by henk-van-der-vaart** [comment]
> We NEC Nederland B.V. are a current user (from start of availability) of the API v1 .NET client (available as NuGet).
> Since API v1 support will stop end 2021 we hope API v2 .NET client will be available in time given us enough time to adapt our tooling (code changes, review and testing).

Is there maybe a status update, when is topic addressed (any news about the planning / road-map)?

**Comment by ira-sem** [comment]
Hi Henk! The API v2 .NET Client is already on our roadmap, but at the moment it is hard to say ETA

**Comment by andrii-bodnar** [comment]
Hi @henk-van-der-vaart!

We have just released a new version of Crowdin .NET API Client - 2.0.0. This version supports API v2. You can find more details and some examples in the Readme of this repo.

**Comment by henk-van-der-vaart** [comment]
Hello @andrii-bodnar - Thanks for informing and releasing the .NET API 2.0 client and associated NuGet package. I have informed the responsible developers on our site.
