### ISSUE TITLE
EnterpriseInviteUserRequest misses "adminAccess" property

### ISSUE THREAD

**Issue by bZverok** [crowdin/crowdin-api-client-dotnet#191]
Class EnterpriseInviteUserRequest does not have property for making invited user an admin, like it is said in the API docs: https://developer.crowdin.com/enterprise/api/v2/#operation/api.users.post

**Comment by Riju-bak** [comment]
This [PR](https://github.com/crowdin/crowdin-api-client-dotnet/pull/192) should fix it.
