### ISSUE TITLE
Report Settings Template: add the `isPublic` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#198]
The Report Settings Template API now supports the ability to create public templates. We need to add support for the `isPublic` property to this Crowdin API client.

**References:**

- [Add Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.post)
- [Get Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.get) (response)

**Comment by Zahid92** [comment]
Hi @andrii-bodnar,
I wanted to work on this issue could you assign it to me?
