### ISSUE TITLE
Source Files: add the `context` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#200]
The Source Files API now supports the possibility to specify the `context` for the whole file. We need to add support for the `context` property to this Crowdin API client.

**References:**

- [Add File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.post)
- [Edit File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.patch)
- [Get file](https://developer.crowdin.com/api/v2/#operation/api.projects.files.get) (response)

**Comment by kisharnath** [comment]
I would like to work on this

**Comment by andrii-bodnar** [comment]
Similar PRs: #199, #192, #181

**Comment by andrii-bodnar** [comment]
@Zahid92 would you like to take this as well?

**Comment by Zahid92** [comment]
Hi @andrii-bodnar, yes gladly.
