### ISSUE TITLE
`WorkflowsApiExecutor` is not accessible in the `CrowdinApiClient` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#203]
References:

- [`CrowdinApiClient.cs`](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/CrowdinApiClient.cs)
- [`WorkflowsApiExecutor.cs`](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/Workflows/WorkflowsApiExecutor.cs)

**Comment by Zahid92** [comment]
Hi @andrii-bodnar I would like to work on this issue.
Could you elaborate some more about what are we trying to achieve here ?

**Comment by andrii-bodnar** [comment]
Hi @Zahid92 great, thank you!

Currently, the `Workflows` API can't be called because it was accidentally not initialized in the client. Like this: `await client.Workflows`

For example, how it works for the Labels API:

```c
ResponseList<StorageResource> storages = await client.Storage.ListStorages();
```
