### ISSUE TITLE
Strings translations APIs: add new parameters support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#206]
Several String Translation API endpoints have been enhanced with new parameters support: `labelIds`, `excludeLabelIds`. These parameters should be added to this API client.

**References:**

- [List Translation Approvals](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.approvals.getMany)
- [List Translation Votes](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.votes.getMany)

**Comment by Riju-bak** [comment]
@andrii-bodnar Can work on this?

**Comment by andrii-bodnar** [comment]
@Riju-bak sure, assigning it to you, thank you!
