### ISSUE TITLE
NuGet package: add Readme

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#208]
Currently, the Readme section on the NuGet package page contains only a short and not really usable description:

![screenshot-www nuget org-2023 11 02-09_54_49](https://github.com/crowdin/crowdin-api-client-dotnet/assets/29282228/fb8a68f2-dbb8-4deb-bf33-390e1820bf1f)

We should find a way to include the repository Readme in this Readme section on NuGet.

https://www.nuget.org/packages/Crowdin.Api/

**Comment by erayaydogdu** [comment]
Hi @andrii-bodnar I've created a PR that I thought could be help..
