### ISSUE TITLE
Applications API: add support for new endpoints

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#211]
Crowdin has recently released new endpoints for the Applications API. We need to add support for them in the Crowdin API client as well.

**API reference:**

- [List Application Installations](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.getMany)
- [Install Application](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.post)
- [Get Application Installation](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.get)
- [Delete Application Installation](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.delete)
- [Edit Application Installation](https://developer.crowdin.com/api/v2/#operation/api.applications.installations.patch)

**Comment by andrii-bodnar** [comment]
Hi @touseefkhanstewart!

Thanks for your interest in this project. You can choose any open issue you like. I would recommend starting with the [contributing guidelines](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/CONTRIBUTING.md) and checking out the [latest pull requests](https://github.com/crowdin/crowdin-api-client-dotnet/pulls?q=is%3Apr+is%3Aclosed).

**Comment by andrii-bodnar** [comment]
Hi @touseef4pk, any updates on this?

**Comment by Zahid92** [comment]
Hi @andrii-bodnar, could I look into this ?

**Comment by andrii-bodnar** [comment]
Hi @Zahid92, sure, assigning it to you. Thank you!
