### ISSUE TITLE
StringBatchOperations return null

### ISSUE THREAD

**Issue by kevinLourencoDev** [crowdin/crowdin-api-client-dotnet#212]
Hi, 

In both version 2.18 and 2.19,  StringBatchOperations seems to not send the correct ResponseList<SourceString> and send return result: null

Here is the simple client call: 

```
        public Task<ResponseList<SourceString>> BulkEditSourceStrings(int projectId, List<StringBatchOpPatch> patches)
        {
            return _client.SourceStrings.StringBatchOperations(projectId, patches);
        }
```

And there is how we created patches: 

```
 var patches = sourceStrings.Select(sourceString => new CrowdinSourceStrings.StringBatchOpPatch()
            {
                Operation = Crowdin.Api.PatchOperation.Add,
                Value = new CrowdinSourceStrings.SourceString()
                {
                    Identifier = "test",
                    Text = "test",
                    Context = "test",
                    FileId = 1,
                    IsHidden = false
                }
            }
                ).ToList();

            var response = await _crowdinClientWrapper.BulkEditSourceStrings(projectId, patches);
```

Patches seem to be well formatted if we consider it's required to be only an array of {Crowdin.Api.SourceStrings.StringBatchOpPatch} following https://developer.crowdin.com/api/v2/#operation/api.projects.strings.post 

High chance the feature is simply not working, since my implementation is simple. Let me know if you need more informations !

**Comment by andrii-bodnar** [comment]
@kevinLourencoDev thanks a lot for the details and the confirmation!

**Comment by kevinLourencoDev** [comment]
@andrii-bodnar do you have any visibility on this error base on the priority of it? Would you need more help to fix it?

**Comment by andrii-bodnar** [comment]
@kevinLourencoDev since this is an API Client issue, we'd be happy to accept contributions!

Feel free to read the [contributing guidelines](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/CONTRIBUTING.md) for more details.

**Comment by Zahid92** [comment]
Hi @kevinLourencoDev,

Could you try using this
 ```
var patches = sourceStrings.Select(sourceString => new CrowdinSourceStrings.StringBatchOpPatch()
            {
                Operation = Crowdin.Api.PatchOperation.Add,
                Value = new CrowdinSourceStrings.AddStringRequest()
                {
                    Identifier = "test",
                    Text = "test",
                    Context = "test",
                    FileId = 1,
                    IsHidden = false
                }
            }
                ).ToList();

            var response = await _crowdinClientWrapper.BulkEditSourceStrings(projectId, patches);
```
As new source strings are added using AddStringRequest Object rather than SourceString.

**Comment by Zahid92** [comment]
Hi @andrii-bodnar, I think the user must not be able to instantiate a source string object. It should always come from API only.
