### ISSUE TITLE
String-based API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#214]
Crowdin has recently released a new type of projects - **String-based**.

In string-based projects, the focus is on managing translatable content as individual strings rather than source files. In this project type, after uploading source files, Crowdin parses them into source strings. Unlike file-based projects, source files aren’t stored, and the emphasis is on managing the content at the string level. This approach is beneficial when dealing with projects that involve continuous content updates, dynamic content, or where a string-oriented structure is preferred.

As a result, the API differs a bit from the file-based projects. Most of the endpoints are the same, but some endpoints have different parameters or return different responses, some endpoints are not available at all, and some new endpoints are available only for string-based projects.

We should update the API clients to support string-based projects as well.

**Progress:**

String-based support for (#224): 
- [x]  Clients API
- [x] Bundles
- [x] Distributions
- [x] Labels
- [x] Machine Translations

Remaining String-based support for:
- [x] Projects api
- [x] Branches api
- [x] Reports api
- [x] String translations api
- [x] Tasks api
- [x] Translation status api
- [x] Translations api
- [x] Webhooks api
- [x] Strings api

**References:**

- [Crowdin API v2 Reference (String-based)](https://developer.crowdin.com/api/v2/string-based/)
- [Crowdin API v2 Reference (File-based)](https://developer.crowdin.com/api/v2/)

**It has been implemented for the following clients:**

- https://github.com/crowdin/crowdin-api-client-js/pull/328
- https://github.com/crowdin/crowdin-api-client-java/pull/212

**Comment by Zahid92** [comment]
Hi @andrii-bodnar, I would like to try implementing this as well.

**Comment by andrii-bodnar** [comment]
Hi @Zahid92, awesome, thank you!

Assigning it to you. Feel free to contact me here if you have any questions.

**Comment by andrii-bodnar** [comment]
Hi @Zahid92 do you have any updates on this?

**Comment by Zahid92** [comment]
Sorry, I got busy with some personal stuff. 
I have gone through with the mentioned PR's and will make the changes accordingly.

**Comment by Zahid92** [comment]
Hi @andrii-bodnar in [ ListLabels](https://developer.crowdin.com/api/v2/string-based/#operation/api.projects.labels.getMany) isSystem is an enum for {0, 1}. 
Should it be a bool instead of enum??

**Comment by andrii-bodnar** [comment]
Hi @Zahid92, well, nice question :)

For some unknown reason it was implemented this way, but it's actually better to have the boolean type here.
