### ISSUE TITLE
List Language Translations API: support new parameters

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#219]
Crowdin has recently added new parameters to the List Language Translations API endpoint:

- `branchId`
- `directoryId`

These parameters should also be supported in the Crowdin API client. It would also be good to check if other parameters are supported.

**References:**

- [List Language Translations](https://developer.crowdin.com/api/v2/#operation/api.projects.languages.translations.getMany)

**Comment by Riju-bak** [comment]
Hi @andrii-bodnar, can I work on this?

**Comment by andrii-bodnar** [comment]
Hi @Riju-bak, sure, thank you!

**Comment by Riju-bak** [comment]
@andrii-bodnar Here's the [PR](https://github.com/crowdin/crowdin-api-client-dotnet/pull/220)
