### ISSUE TITLE
Fields API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#223]
Crowdin has recently added a new feature called custom attributes for entities. This feature also has a set of API endpoints to manage custom attributes.

The API client should be updated to support these endpoints.

**References:**

- [List Fields](https://developer.crowdin.com/enterprise/api/v2/#operation/api.fields.getMany)
- [Add Field](https://developer.crowdin.com/enterprise/api/v2/#operation/api.fields.post)
- [Get Field](https://developer.crowdin.com/enterprise/api/v2/#operation/api.fields.get)
- [Delete Field](https://developer.crowdin.com/enterprise/api/v2/#operation/api.fields.delete)
- [Edit Field](https://developer.crowdin.com/enterprise/api/v2/#operation/api.fields.patch)

Only for Crowdin Enterprise.

**Comment by Riju-bak** [comment]
@andrii-bodnar Can I work on this?

**Comment by andrii-bodnar** [comment]
@Riju-bak sure, thank you!

**Comment by Riju-bak** [comment]
@andrii-bodnar As per the docs for [Edit Field API](https://developer.crowdin.com/enterprise/api/v2/#operation/api.fields.patch) it seems that only the `name` of a Field can be edited.

Could you please confirm if this is as expected, or should the api also allow editing the other properties - `slug`, `description`, `type` , `config` and `entities`?

**Comment by andrii-bodnar** [comment]
@Riju-bak thanks for pointing this out! The API allows editing everything except the `slug` and `type`.

**Comment by Riju-bak** [comment]
Got it, thanks

**Comment by Riju-bak** [comment]
@andrii-bodnar [PR](https://github.com/crowdin/crowdin-api-client-dotnet/pull/229) is ready for review
