### ISSUE TITLE
Custom fuzzy match types in translation cost report

### ISSUE THREAD

**Issue by adamcsillag** [crowdin/crowdin-api-client-dotnet#225]
Hi,

Is it possible to have custom fuzzy match types in a TranslationCostsPostEditingGenerateReportRequest? In NetRateSchemes it is possible to specify SuggestionMatch values, however there are only MatchType.Option_99_82 and MatchType.Option_81_60 fuzzy match types. On the UI It's possible to add custom match types:

![image](https://github.com/crowdin/crowdin-api-client-dotnet/assets/696846/2f798a7d-d089-4302-a70f-92e8b596c556)

**Comment by andrii-bodnar** [comment]
@adamcsillag thanks for pointing this out!

The API documentation is a little misleading in this case. It should be possible to specify custom match types, not just `100` and `99-82`.

The current implementation doesn't allow such values, so it should be improved to allow custom ranges as well.
