### ISSUE TITLE
DeleteStorage and GetStorage must use long instead of int

### ISSUE THREAD

**Issue by Cancri55E** [crowdin/crowdin-api-client-dotnet#241]
After this PR https://github.com/crowdin/crowdin-api-client-dotnet/pull/240 you must fix DeleteStorage and GetStorage methods to use long instead of int for storageId

**Comment by Surya056** [comment]
I would like to contribute by fixing this bug.

**Comment by Surya056** [comment]
Please find the below pull request for the same, please review and let me know if any other changes to be done : 
https://github.com/crowdin/crowdin-api-client-dotnet/pull/242
