### ISSUE TITLE
Assembly in nuget is not signed

### ISSUE THREAD

**Issue by dsvictory** [crowdin/crowdin-api-client-dotnet#249]
Hi!

In our company we interract with CrowdIn from projects which are signed and we can't use CrowdIn.Api library, because it is not signed. We get this error because of that:

`Could not load file or assembly 'Crowdin.Api, Version=2.24.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`

Could you, please, publish to nuget a signed dll?

Other options to avoid this problem are pretty exhausted.)

**Comment by andrii-bodnar** [comment]
Hi!

Could you please provide some examples of Nuget libraries that provide such signed DLLs?

Some guides and more examples (including GitHub Action workflows) are also welcome.

**Comment by dsvictory** [comment]
All these libraries are signed. They all have a PublicKeyToken in their strong names. And that's why we can use it in our signed projects without any problems.

[Polly](https://www.nuget.org/packages/polly/)
[Sentry](https://www.nuget.org/packages/Sentry)
[Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json)

Here is an official doc about signing. 
[MSDN Signing assembly](https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name)

I don't have appropriate experience with GitHub Actions, but I'll try to find something useful.

**Comment by andrii-bodnar** [comment]
We currently do not have plans to support strong name signing for our assemblies, as it adds significant maintenance overhead, especially regarding key management and security. For now, you can fork the repository and sign the assembly yourself to address your specific use case.

We hope this helps, and we appreciate your understanding.
