### ISSUE TITLE
Invalid MediaType when calling EditTaskArchivedStatus

### ISSUE THREAD

**Issue by jerome-raffalli** [crowdin/crowdin-api-client-dotnet#38]
Hello,
calling EditTaskArchivedStatus raises an exception about mediatype.

Patch in CrowdinApiClient.cs

```
        private HttpContent CreateJsonContent(object body, bool isPatch = false)
        {
            string bodyJson = JsonConvert.SerializeObject(body, DefaultJsonSerializerOptions);

            MediaTypeHeaderValue contentType = isPatch
//                ? MediaTypeHeaderValue.Parse("application/json-patch+json")
                ? MediaTypeHeaderValue.Parse("application/json")
                : DefaultContentType;
            
            return new StringContent(bodyJson, Encoding.UTF8, contentType.MediaType);
        }

```

**Comment by andrii-bodnar** [comment]
Hi @jerome-raffalli, thanks a lot for your involvement! We will fix these issues ASAP

**Comment by jerome-raffalli** [comment]
Hello Andrii, Crowdin is a great tool and having the Client API in opensource is really a good point. Thank you.

**Comment by innomaxx** [comment]
Hi @jerome-raffalli, which OS and .NET runtime versions are you using? I had just tested `MediaTypeHeaderValue.Parse("application/json-patch+json")` on .NET 5 and it works fine.

**Comment by jerome-raffalli** [comment]
Hello Max,

I am using visualstudio 2022 on windows server 2019
test program is for .NET6, but my application is for .NET5 and it hangs too.
I just rechecked and replacing "json-patch+json" with "json" doesn't hang but does nothing (the isArchived flag remains null)
so there is a problem too.

my test code : 

```
using Crowdin.Api;
using Crowdin.Api.ProjectsGroups;
using Crowdin.Api.Tasks;

var client = new CrowdinApiClient(new CrowdinCredentials
{
    AccessToken = "a5c783cc3d54aa5d68e7b6da6809fbb0acb570be6229bc84fb18432d95df5dec94ed246cd1769f5d",
    Organization = ""
});

var L = new List<TaskArchivedStatusPatch>();
L.Add(new TaskArchivedStatusPatch { Operation= PatchOperation.Replace, Path= TaskArchivedStatusPatchPath.IsArchived, Value = true });
await client.Tasks.EditTaskArchivedStatus(499200, 16, L);

var TK = await client.Tasks.ListTasks(499200);

```

Exception details

```
Crowdin.Api.CrowdinApiException
  HResult=0x80131500
  Message=Unsupported Content-Type Header
  Source=Crowdin.Api
  StackTrace:
   at Crowdin.Api.CrowdinApiClient.<CheckDefaultPreconditionsAndErrors>d__90.MoveNext() in Q:\crowdin-api-client-dotnet\src\Crowdin.Api\CrowdinApiClient.cs:line 327

```

**Comment by andrii-bodnar** [comment]
@jerome-raffalli please revoke your access token specified in your comment for the security reasons

**Comment by innomaxx** [comment]
@jerome-raffalli please try `fix/patch-routes-content-type` branch and let us know if the problem is solved or not

**Comment by andrii-bodnar** [comment]
Hi @jerome-raffalli!

Have you tried the proposed solution? Also, you can check the code with the fix in linked PR.

**Comment by jerome-raffalli** [comment]
Hello Andrii, yes I checked this code and it's ok for me.
