### ISSUE TITLE
invalid Request class member `ExportApprovedOnly` for `ExportProjectTranslation` 

### ISSUE THREAD

**Issue by penspanic** [crowdin/crowdin-api-client-dotnet#48]
I tried to call API `ExportProjectTranslation` with below code, but got response error.

```csharp
            DownloadLink exportedLink = await apiClient.Translations.ExportProjectTranslation("ProjectId",
                new ExportProjectTranslationRequest()
                {
                    TargetLanguageId = "en",
                    ExportApprovedOnly = true, // seems invalid paramter for current Crowdin API Service.
                });
```
and error detail:
<html>
<body>

Url | https://@@@@.crowdin.com/api/v2/projects/4/translations/exports
-- | --
Method | POST
Status | Error
Message | Bad Request
Authorization Type | Personal Access Token

Request details | {   "targetLanguageId": "en",   "exportApprovedOnly": true }
Errors | {   "errors": [     {       "error": {         "key": "exportApprovedOnly",         "errors": [           {             "code": "notFound",             "message": "Field 'exportApprovedOnly' Not Found"           }         ]       }     }   ] }

</body>
</html>

Please check this issue.

**Comment by zozulka** [comment]
Hi there,

Could you please tell us which error did you get to investigate this issue?

**Comment by andrii-bodnar** [comment]
Hi @penspanic!

The `ExportApprovedOnly` parameter is available only for crowdin.com. For Crowdin Enterprise the `ExportWithMinApprovalsCount` (minimum count of approvals for translation to be exported) request parameter should be used.

[Export Project Translation - enterprise docs](https://support.crowdin.com/enterprise/api/#operation/api.projects.translations.exports.post)

**Comment by penspanic** [comment]
@andrii-bodnar Thanks for reply.

So, when using Crowdin Enterprise,
Is this `crowdin-api-client-dotnet` sdk might not suitable for some APIs?

I used `CrowdinApiClient.SendPostRequest` method and get success result, but want to know that any suitable sdk for Crowdin Enterprise is exists.

**Comment by andrii-bodnar** [comment]
@penspanic, `crowdin-api-client-dotnet` is suitable for both Crowdin APIs and Crowdin Enterprise APIs.

In your case, the code should look something like that:

```csharp
DownloadLink exportedLink = await apiClient.Translations.ExportProjectTranslation("ProjectId",
    new ExportProjectTranslationRequest()
    {
        TargetLanguageId = "en",
        ExportWithMinApprovalsCount = 1,
    });
```
