### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#8]
It would be good to write some Unit tests for the classes of this client.
Write tests for most important parts of *src/Crowdin.Ap*i.

**Comment by jasonleenaylor** [comment]
Do you have a preferred Unit testing framework? NUnit or XUnit for example?

**Comment by andrii-bodnar** [comment]
@jasonleenaylor At the moment there is no preferred framework. Which will be better?

**Comment by jasonleenaylor** [comment]
I think XUnit fits the project better.
