### ISSUE TITLE
.NET 5.0 Out of Support

### ISSUE THREAD

**Issue by gauravagrwal** [crowdin/crowdin-api-client-dotnet#80]
Hi,

I saw that that projects `Crowdin.Api.Samples.csproj` and `Crowdin.Api.Tests.csproj` are still using .NET 5.0 version.
As support for .NET 5.0 version is already ended back in May, 2022. [🔗](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/)

I suggest these projects can be migrated to current .NET 6.0 version.

**Comment by innomaxx** [comment]
Hi @gauravagrwal,

Thanks for your response. We will migrate projects to .NET 6.0 LTS ASAP

**Comment by innomaxx** [comment]
https://github.com/crowdin/crowdin-api-client-dotnet/pull/98
