### ISSUE TITLE
Increase tests coverage for the `ReportsApiExecutor.cs` class

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#83]
The coverage of this class is low and it would be great to fully cover it by writing Unit tests.

- [Actual coverage](https://app.codecov.io/gh/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/Reports/ReportsApiExecutor.cs)
- [ReportsApiExecutor.cs](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/Reports/ReportsApiExecutor.cs)
- [Existing tests](https://github.com/crowdin/crowdin-api-client-dotnet/tree/main/tests/Crowdin.Api.Tests/Reports)

**Comment by gauravagrwal** [comment]
Hi @andrii-bodnar, I would like to work on this issue. Can you please assign it to me?

**Comment by andrii-bodnar** [comment]
Hi @gauravagrwal, sure, thank you!
