### ISSUE TITLE
Remove deprecated `eta` response property usage

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-dotnet#99]
https://github.com/crowdin/crowdin-api-client-dotnet/search?q=eta

This property is being deprecated and should be removed. Actually, it never provided any usable result so probably no one is dependent on it.

**Comment by JoePorterDev** [comment]
I'll take this if that's all good.

**Comment by andrii-bodnar** [comment]
@JoePorterDev sure, thank you!
